### ISSUE TITLE
Calling the Invoke API failed with message: Rate Exceeded.

### ISSUE THREAD

**Issue by Barneel** [alexa/skill-sample-python-fact#10]
Hi There,

I am fairly new to this, so apologies if this is a basic fix... I get stuck on section 2.8.

When I click the 'test' button, I get the error message:
"Calling the Invoke API failed with message: Rate Exceeded."

Is this a problem? Am I going to have problems later on if I don't resolve this? How can I resolve this?

Thanks for any help people can give! and please let me know if there is any more info you need.

**Comment by franklin-lobb** [comment]
This sounds like something specific to your AWS account. (Do you have lots of other activity going on in your account which would push you to that threshold?)  I would suggest checking the AWS forums or contacting AWS support for ideas on what to do next.
