### ISSUE TITLE
I have created a custom skill, how can I invoke the Intent?

### ISSUE THREAD

**Issue by yanggewei** [alexa/skill-sample-python-fact#11]
I have created a custom skill, and add a Intent, I want to invoke the Intent by speaking.
the custom skill name is : media center
the Sample Utterances of the Intent is : open video box

now, I say : alexa, open media center
the alexa response as I set in the Console；
then I say : open video box
then alexa will invoke the Intent. It works well.
But, I want to combine "skill name" and "Sample Utterances of the Intent" in a sentence, it does not work!
for example, I say : alexa, ask media center for open video box,
or I say : alexa, open video box in media center,
it does not work, alexa cannot undersdand what I speak, I want to know why, and how can I invoke the Intent in the second way.

**Comment by franklin-lobb** [comment]
Both open and ask are launch phrases, so I suspect that is causing the problem when they both are in the same single shot utterance.  If you want to use a single shot, you might try adding 'video box' as a sample utterance for your intent, and then say 'Alexa, ask media center for video box'.

**Comment by franklin-lobb** [comment]
I meant to include this link to the documentation which has additional information about what you're trying to do: https://developer.amazon.com/docs/custom-skills/understanding-how-users-invoke-custom-skills.html#cert-invoke-specific-request

**Comment by franklin-lobb** [comment]
closed due to age
