### ISSUE TITLE
Zip only contents of folder (in WIndows)

### ISSUE THREAD

**Issue by rajurajvijay619** [alexa/skill-sample-python-fact#12]
*Zip the contents of the skill_env folder. Remember to zip the contents of the folder and NOT the folder itself.*

How do i do this? In windows? Because when I zip it, the whole directory is zipped to give *skill_env.zip*

**Comment by rajurajvijay619** [comment]
for any one facing this issue in windows, you can use : 
**jar -cMf targetArchive.zip sourceDirectory**
In place of sourceDirectory,you can specify "*"

**Comment by franklin-lobb** [comment]
closing due to age
