### ISSUE TITLE
Certification not passed

### ISSUE THREAD

**Issue by rajurajvijay619** [alexa/skill-sample-python-fact#13]
I used the same procedure.
I only changed the data(facts)

I got the following feedback.
1) After the skill completes a task, the session remains open with no prompt to the user. The skill must close the session after fulfilling requests if it does not prompt the user for any input.
2) When invoking the skill with one or more of the intent(s) or sample utterances, the skill’s response is irrelevant to the request or contains an error.

**Comment by franklin-lobb** [comment]
closed due to age.
