### ISSUE TITLE
Wrong tutorial - New Intends doesn't work

### ISSUE THREAD

**Issue by utest1909** [alexa/skill-sample-python-fact#14]
Following this tutorial results in these problems:
- "open -invocation name-" --> Alexa speaks the first phrase
- "Alexa, ask -invocation name- to -intent phrase-" -> Alexa speaks EXCEPTION_MESSAGE

Submitting it to publish gets refused with that comment:
The example phrases that you choose to present to users in the Alexa app must be selected from your sample utterances. For example: "Alexa, ask {your invocation name} to {sample utterance present in your intent}."Please see our documentation for more information on ensuring your sample utterances support invocation phrases. Please also see our blogpost for more guidance on creating example phrases.

**Comment by franklin-lobb** [comment]
There was an error in the canHandle intent name check.  This has been fixed.
