### ISSUE TITLE
Unrefrenced slot

### ISSUE THREAD

**Issue by subbu-art** [alexa/skill-sample-python-fact#30]
when I try to build my bot im getting the following issue.
"The slot "ability" in intent "capability" is not referenced in any slot or intent sample."

**Comment by franklin-lobb** [comment]
You've defined a slot for an intent, but haven't referenced it in any of the sample utterances, or slot elicitation utterances.  In the developer console, add another utterance that is appropriate to your intent that uses the slot.  for example `are you able to {ability}` or whatever makes sense for your intent.

**Comment by ajot** [comment]
We're closing this pull request _for now_ because of inactivity. 

@subbu-art  we can always reopen it though! :) Please update the pull request if you're still having issues with this. If you need any help, please hit us up on twitter @AlexaDevs
