### ISSUE TITLE
documentation: Interaction Model

### ISSUE THREAD

**Issue by andreasherbst** [alexa/skill-sample-python-fact#4]
documentation: Interaction Model link not working
"
In the textfield provided, replace any existing code with the code provided in the Interaction Model, then click "Apply Changes" or "Save Model"."
hold an invalid link

**Comment by aaronredmond** [comment]
Hi @andreasherbst , the intent needs to be updated. Please see my forked version for an updated version

**Comment by franklin-lobb** [comment]
this was fixed in a previous update.
