### ISSUE TITLE
`dialogState` is not changing to `COMPLETED`

### ISSUE THREAD

**Issue by Nikhil-Wagh** [alexa/skill-sample-python-fact#5]
The `dialogState` always remains either `"STARTED"` or `"IN_PROGRESS"`, it is never switched to `"COMPLETED"`. There have been multiple reports of the same issue. See these (https://stackoverflow.com/questions/48897675/the-last-slot-in-an-alexa-skill-filled-by-the-dialog-model-always-throws-an-issu, https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/177)

[Here](https://github.com/Nikhil-Wagh/Alexa-Flick/blob/6ad3cb0cfb58b1368f55448840682d49ca188ab3/events/errorInput.json#L121) is the JSON Input generated by my skill in the Skill Tester. Please see the section where even after **confirming** the `slots` the `dialogState` is still `"IN_PROGRESS"`. 

[Here](https://github.com/Nikhil-Wagh/Alexa-Flick/blob/master/lambda_function.py) is my complete code. The issue may be in line 109 or 339 (If it's in my code). 
Please tell me what should I do?

**Comment by isaacdchan** [comment]
Hey Nikhil,

Did you ever get this problem solved? I'm having the same issue.

**Comment by Nikhil-Wagh** [comment]
It seems like the last step is not shown on Alexa Skill Tester. When all slots are acquired it does change to `COMPLETED`, but it is not shown. Also the result is also not shown (cards, etc). But when you test it on echoism, they show up.

**Comment by isaacdchan** [comment]
How do you access your Alexa Skill on echoism? And has the not changing to ```COMPLETED``` only in the skill tester been confirmed? Thank you man

**Comment by franklin-lobb** [comment]
If you log in to echosim.io using the same account as you've used in the Alexa Developer Portal, and the skill is enabled for testing, you can invoke it like any other skill, e.g. open <invocation name>

**Comment by Nikhil-Wagh** [comment]
No, It hasn't been confirmed. It's just my personal experience.

**Comment by Bubelbub** [comment]
Yeah I have the same issue.
Its very bad that the testing tool of Amazon is not working as a real device.

**Comment by Ronoir** [comment]
same

**Comment by dillonharlessNHRMC** [comment]
Similar issue here... Using console.log(), it seems like after I .addDelegateDirective(currentIntent), it never returns to the intent after filling slots.

**Comment by jamezrin** [comment]
I'm having this issue when using the Java SDK, the dialog state never turns to completed after filling every slot... I guess I will check the value of every single one of them...

**Comment by AnkitBajpaii** [comment]
same issue in December'2018.

**Comment by franklin-lobb** [comment]
I just try testing this and see COMPLETED in the intent (I was using auto-delegation), so perhaps has been fixed.

**Comment by Nikhil-Wagh** [comment]
Since this has been fixed, I'll be closing this issue.

**Comment by dilunika** [comment]
Yes it is fixed for auto-delegation, but not when auto-delegation is disabled. Is there a way that I can programmatically set this state to complete? I tried blindly setting `request.dialogState = 'COMPLETED';`But no luck. 
I might be a very naive Alexa developer, but missing this sort of information makes Alexa developer's life very hard.

**Comment by jashton-vintel** [comment]
I appear to be having a similar issue when auto-delegation is disbled.. was there any formal update for this?
